-- V1: SmartPark Base Schema

-- Users Table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Parking Lots Table
CREATE TABLE parking_lots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    address VARCHAR(500) NOT NULL,
    city VARCHAR(100) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    total_slots INTEGER NOT NULL,
    rate_per_hour DECIMAL(10, 2) NOT NULL,
    extra_rate_per_minute DECIMAL(10, 2) DEFAULT 2.00,
    buffer_minutes INTEGER DEFAULT 15,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Slots Table
CREATE TABLE slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parking_lot_id BIGINT NOT NULL,
    slot_number VARCHAR(10) NOT NULL,
    floor_level VARCHAR(10) DEFAULT 'G',
    slot_type VARCHAR(20) DEFAULT 'REGULAR',
    is_active BOOLEAN DEFAULT TRUE,
    CONSTRAINT fk_slots_parking_lot FOREIGN KEY (parking_lot_id) REFERENCES parking_lots(id),
    CONSTRAINT uk_slots_lot_number UNIQUE (parking_lot_id, slot_number)
);

-- Bookings Table
CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_ref VARCHAR(36) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    slot_id BIGINT NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    actual_exit_time TIMESTAMP,
    buffer_minutes INTEGER DEFAULT 15,
    status VARCHAR(20) NOT NULL,
    base_amount DECIMAL(10, 2) NOT NULL,
    extra_charge DECIMAL(10, 2) DEFAULT 0.00,
    total_amount DECIMAL(10, 2) NOT NULL,
    qr_token TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bookings_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_bookings_slot FOREIGN KEY (slot_id) REFERENCES slots(id)
);

-- Payments Table
CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL,
    payment_ref VARCHAR(255) NOT NULL UNIQUE,
    gateway VARCHAR(50) DEFAULT 'STRIPE',
    amount DECIMAL(10, 2) NOT NULL,
    currency VARCHAR(10) DEFAULT 'INR',
    status VARCHAR(20) NOT NULL,
    gateway_response TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payments_booking FOREIGN KEY (booking_id) REFERENCES bookings(id)
);

-- Slot Locks Table (Concurrent Booking Prevention)
CREATE TABLE slot_locks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    lock_start TIMESTAMP NOT NULL,
    lock_expiry TIMESTAMP NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    CONSTRAINT fk_slot_locks_slot FOREIGN KEY (slot_id) REFERENCES slots(id),
    CONSTRAINT fk_slot_locks_user FOREIGN KEY (user_id) REFERENCES users(id)
);
